### ISSUE TITLE
new feature suggestion: OS command and retrieve Operating System Messages

### ISSUE THREAD

**Issue by ScYang1991** [zhmcclient/zhmc-ansible-modules#565]
It would be very helpful if sending OS command and Retrieving Operating System Messages features can be added to this collection. Think IPLs and SHUTDOWNs that require certain OS commands to be executed can be automated.
Those features should be available from HMC web API from 2.14.1.

Thanks.

**Comment by andy-maier** [comment]
Hello @ScYang1991
The question is how should an Ansible module be designed for that, since Ansible is normally used to get a system or resource to a desired end state, but this is more action oriented.

Let me give an idea how I think this could be designed, just to have something to discuss, but I'm really interested in your ideas on that:

One idea is to have a module that checks the console for a specific expected OS message, and if present, it sends a particular OS command to the console. Interesting questions are:
- Does the command to be sent needs to be formed by using items from the actual OS message?
- How far back in the stream of OS messages shuld the expected message to be looked for?
- Is regexp pattern matching needed to find the expected OS message?
- Is a timeout needed to specify for how long the module should wait for the expected message before it fails?

**Comment by ScYang1991** [comment]
@andy-maier 
Thank you for your response.
I understand that retrieving OS command's system response would be difficult.
Currently I am using combination of playbook and python script for the purpose with below logic.

1. retrieve OS console message using zhmcclient open_os_message_channel & NotificationReceiver
2. execute OS command using zhmcclient send_os_command
3. retrieve OS console message using zhmcclient open_os_message_channel & NotificationReceiver
4. compare difference between result list of 1. and 3. (loop until it finds a record for given string such as message ID for a given time of attempts & interval) loop is done by using ansible playbook feature as below
```
  until: after_command.stdout | from_json | difference(before_command.stdout) | map(attribute='message-text') | list is search('expected response message ID')
  delay: 30
  retries: 5
```
So having "send OS command" and "retrieve OS console message list" independently would be enough for my purpose of use. Dynamically tracking system response would not be required.

Then it would be able to achieve the same result with below logic.

1. retrieve OS console message using "retrieve OS console message list"  module
2. execute OS command using zhmcclient "send OS command" module
3. retrieve OS console message using "retrieve OS console message list"  module
4. compare difference between result list of 1. and 3. with same logic as above.

Thanks.

**Comment by andy-maier** [comment]
Support for "List OS Messages" is being added to the zhmcclient library in PR https://github.com/zhmcclient/python-zhmcclient/pull/1279 (targeted for zhmcclient 1.12.0)

**Comment by andy-maier** [comment]
PR https://github.com/zhmcclient/zhmc-ansible-modules/pull/819 adds support for new Ansible modules that retrieve OS messages for LPARs and DPM partitions. It is targeted for the ibm_zhmc Ansible collection version 1.8.0.

**Comment by andy-maier** [comment]
@ScYang1991 Somehow the request for supporting the sending of OS commands got lost in this discussion. I have created issue #938 for that.

**Comment by andy-maier** [comment]
[ScYang1991](https://github.com/ScYang1991): PR #1033 is adding support for executing OS consosle commands in LPARs and partitions. The new modules return the command output, so you do not have to get and compare the messages in the playbook.
