### ISSUE TITLE
Unable to stop a partition once it's in paused state

### ISSUE THREAD

**Issue by vmorris** [zhmcclient/zhmc-ansible-modules#642]
If a partition in in any of the `STOP_END_STATES`, no attempt to stop it is made. This is a problem, because it's not possible to start a partition unless it's stopped first.

When I run `shutdown -h` in a Linux partition, or I `halt` during a kickstart installation, the partition goes into `paused` state, and then there's no way to restart it through ansible.

Attempting to stop a paused partition results in

```
"msg": "StatusError: Could not get partition 'TA20-demo' into a stopped state, status is: 'paused'"
```

**Comment by andy-maier** [comment]
The zhmc_partition module with `state=stopped` input on an existing partition attempts to stop the partition. If it finds the current partition statuus to be in STOP_END_STATUSES ('stopped', 'terminated', 'paused', 'reservation-error'), it does not do anything, but at the end it still checks for just "stopped" and raises the StatusError exception you have shown above.

That is definitely inconsistent, and does not allow getting out of the 'paused' or 'reservation-error' statuses.

So definitely something needs to be done about that.

**Comment by andy-maier** [comment]
Clarified the partition status with the DPM team:
* The only status values where the partition is not loaded or otherwise resource consuming anymore, are: 'stopped', 'reservation-error'
* In status values 'terminated', 'paused', some resources may still be used.

Bottom line: We should change the valid STOP_END_STATUSES to only be: 'stopped', 'reservation-error'. That will allow a partition in 'terminated' or 'paused' status to be stopped using the Ansible module.

**Comment by andy-maier** [comment]
@vmorris PR https://github.com/zhmcclient/zhmc-ansible-modules/pull/766 addresses the issue.
