### ISSUE TITLE
timeout parameter does not seem to work with zhmc_lpar

### ISSUE THREAD

**Issue by justin-esposito** [zhmcclient/zhmc-ansible-modules#986]
Hello there,

I'm having some issues using the timeout option with the zhmc_lpar module. Given the following:

- name: Load LPARs
  ibm.ibm_zhmc.zhmc_lpar:
    hmc_host: my-hmc-host.ibm.com
    ....
    state: loaded
    timeout: 240
  ....

I'll sometimes get the following:
StatusTImeout: Waiting for LPAR xxxx to reach status(es) '['operating']' timed out after 60 s - current status is 'exceptions'

It appears the timeout parameter is not being passed properly, even though when running the play in verbose mode I can clearly see the timeout value being passed as 240. I've tried different values, and have tried collection versions 1.7 and 1.8.3 with no success. When the HMC is under load, there are times a deactivated LPAR can take longer than 60 seconds to get up to speed.

Any thoughts? Is this user-error or a bug?

**Comment by andy-maier** [comment]
Hi Justin. I'll look into this.

**Comment by andy-maier** [comment]
There are two timeouts:
* "operation timeout" for waiting for the asynchronous HMC job to complete. The "timeout" parameter of the Ansible module is passed on as the operation timeout. If that timeout expires, `OperationTimeout` is raised. That is not what happens in your case.
* "status timeout": After the asynchronous HMC job is complete, the zhmcclient waits for the LPAR status to get into the desired state. In case of `state=loaded`, that is status "operating" (and if the `allow_status_exceptions` Ansible module parameter is set, in addition status "exceptions". There is currently no support to set the status timeout in the Ansible module parameters, so it uses its default of 60 seconds. If it expires, `StatusTimeout` is raised. That is the timeout you get.

So what happens is that for some reason, your LPAR does not get into status "operating" after reporting the completion of the load.

In theory, the hMC should not even have any delay in LPAR status change after reporting the completion of the async load operation. But experience shows that there may be a delay of a few seconds. Because in our environments, that delay was never more than a few seconds, we did not provide a means to set the status timeout as an Ansible module parameter.

-> Can you please go to the HMC to find out what the LPAR status is right after when the status timeout occurs, and also whether the LPAR status changes after some time?

**Comment by justin-esposito** [comment]
Hey Andy,

" Please let me know if on your HMC, the status "exceptions" turns into "operating" after some time. In that case, we need to provide a means to control the status timeout as a new Ansible module parameter."

Yes, this is the case. In our scenario, we are loading a lot of LPARs all at once (this being used for DR), and there is also automation handling things behind the scenes as the LPAR loads up (i.e. XCF reconfiguration, JES reconfiguration, etc). Due to the excessive load as well as delay of automation handling some of the reconfiguration work, the LPARs remains in an "exception" status for a minute or two. 

Being able to account for this would be very helpful!

**Comment by andy-maier** [comment]
Hi Justin. We discussed this, and we'll provide a timeout parameter for controlling the status wait timeout, and a flag to allow for exceptions.

**Comment by andy-maier** [comment]
PR #1006 Adds new 'status_timeout' and 'allow_status_exceptions' parameters to the zhmc_lpar module.

The PR is targeted for version 1.9.0. If you want to try it out now, you can simply copy the "plugins" directory of the repo with that branch checked out, over the "plugins" directory of your installation of the ibm_zhmc collection. You can find its install location using "ansible-galaxy collection list ibm.ibm_zhmc".

It turned out that the zhmc_lpar module already considered "exceptions" to be an acceptable end status, so the new 'allow_status_exceptions' parameter got a default of True, for backwards compatibility.

I suggest that you use the new 'status_timeout' parameter to increase the timeout above the default 60 seconds, and that you set 'allow_status_exceptions' to False because you want to wait until status "exceptions" turns into something else.

By the way, if you want more control over the LPAR status, you can also use the zhmc_lpar module to poll for the LPAR status using "state=facts", and put that into a retry loop at the Ansible playbook level, leaving the loop based on the value of the "status" property.
